### ISSUE TITLE
Parameter: health-check-timeout seems not to be set on deployment

### ISSUE THREAD

**Issue by mdejavue** [cloudfoundry/multiapps-cli-plugin#152]
### Description
mtad like this:

```
- name: backend
  type: javascript.nodejs
  path: backend
  parameters:
    buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git#v${nodejs-buildpack-version}
    disk-quota: 1G
    health-check-http-endpoint: /cfhealth
    health-check-timeout: 180 # seconds
    health-check-type: http
    instances: 1
    memory: 2G
```

Expected behaviour is the same as setting via CF CLI:
```
cf set-health-check backend http --invocation-timeout 180
```

### Your environment
*	MultiApps CF CLI Plugin version - 2.6.2
*	which CF vendor is used - SAP BTP

### Steps to reproduce
Try health-check parameters in mtad like from above
