### ISSUE TITLE
[FEATURE] env var support in resource config files

### ISSUE THREAD

**Issue by mocotrah** [cloudfoundry/multiapps-cli-plugin#224]
### Description
According to documentation, we can specify the service creation parameters in 2 ways:
https://help.sap.com/docs/btp/sap-business-technology-platform/service-creation-parameters
directly in the mta/mtaext
```
      resources:
        - name: java-uaa
          type: managed-service
          parameters:
            config:
              param1: val1
```
or in a json file:
```
      resources:
        - name: java-uaa
          type: managed-service
          parameters:
            path: <path to file>
```
When using the first method, there is also the possibility to use env variables:
param1: <%= ENV_VAR1111 %>
In my case, in the mta.yml we are able to set the config of a resource (service) by setting a json file:
Example:
```
- name: myserv-ans
    parameters:
      path: ./myconfig.json
```

This file is used as is and no dynamical values can be set.
This is not a mta build request, but a feature to be used during deployment.

Feature request: I would like to have the possibility to use environment variables in the json file.
During deployment, because the json file is referenced in the deployment descriptor, its content would be scanned for environment variables and replaced.

For example if I want to change an url in the json file, I would set:
"url": "${MY_ENV_VAR}"
or
"url": "<%= MY_ENV_VAR %>"
